---
- name: mvn validate
  shell: chdir=/home/ubuntu/GoldenWaste mvn validate

- name: mvn clean
  shell: chdir=/home/ubuntu/GoldenWaste mvn clean

- name: mvn compile
  shell: chdir=/home/ubuntu/GoldenWaste mvn compile

- name: mvn test
  shell: chdir=/home/ubuntu/GoldenWaste mvn test

- name: mvn package
  shell: chdir=/home/ubuntu/GoldenWaste mvn package

- name: "Deploy jar file"
  shell: java -jar /home/ubuntu/GoldenWaste/target/goldenWastedd-0.0.1-SNAPSHOT.jar

- name: Wait for WebApp to start
  wait_for: port=80 timeout=60