---
- name: Set Linux environment variables
  shell: export GOLDEN_DB_URL={{ ansible_host }}

- name: Set Linux environment variables
  shell: export GOLDEN_DB_PORT={{ mysql_port }}

- name: Set Linux environment variables
  shell: export GOLDEN_DB_NAME={{ db_name }}

- name: Set Linux environment variables
  shell: export GOLDEN_DB_USERNAME={{ db_user }}
  
- name: Set Linux environment variables
  shell: export GOLDEN_DB_PASSWORD={{ db_password }}

- name: Clone a github repository
  git:
    repo: 'https://github.com/MohanadSinan/goldenwaste-sda-hackathon.git'
    dest: /home/ubuntu/GoldenWaste
    single_branch: yes
    version: EC2_VPC_v2

- name: mvn validate
  shell: chdir=/home/ubuntu/GoldenWaste mvn validate

- name: mvn clean
  shell: chdir=/home/ubuntu/GoldenWaste mvn clean

- name: mvn compile
  shell: chdir=/home/ubuntu/GoldenWaste mvn compile

- name: mvn test
  shell: chdir=/home/ubuntu/GoldenWaste mvn test

- name: mvn package
  shell: chdir=/home/ubuntu/GoldenWaste mvn package

- name: "Deploy jar file"
  shell: java -jar /home/ubuntu/GoldenWaste/target/goldenWastedd-0.0.1-SNAPSHOT.jar

- name: Wait for WebApp to start
  wait_for: port=80 timeout=60