---
- name: application.properties file
  copy:
    src: /home/ubuntu/GoldenWaste
    dest: /home/ubuntu/GoldenWaste

- name: mvn validate
  shell: chdir=/home/ubuntu/GoldenWaste mvn validate

- name: mvn clean
  shell: chdir=/home/ubuntu/GoldenWaste mvn clean

- name: mvn compile
  shell: chdir=/home/ubuntu/GoldenWaste mvn compile

- name: mvn test
  shell: chdir=/home/ubuntu/GoldenWaste mvn test

- name: mvn package
  shell: chdir=/home/ubuntu/GoldenWaste mvn package

- name:
  become: yes
  become_method: sudo
  template:
    src: goldenwaste.service
    dest: /usr/lib/systemd/system/goldenwaste.service

- name: Enable goldenwaste.service
  become: yes
  become_method: sudo
  shell: systemctl enable goldenwaste.service

- name: Start goldenwaste.service
  become: yes
  become_method: sudo
  shell: systemctl start goldenwaste.service

- name: Wait for WebApp to start
  wait_for: port=80 timeout=60