---
- name: Setting ANSIBLE_INVENTORY environmental configuration
  shell: echo "export ANSIBLE_INVENTORY=/home/ubuntu/GoldenWaste/ansible/hosts/GoldenWasteHosts" >> ~/.profile

- name: Setting ANSIBLE_HOST_KEY_CHECKING environmental configuration
  shell: echo "export ANSIBLE_HOST_KEY_CHECKING=False" >> ~/.profile

- name: Reload .profile file
  shell: . ~/.profile

- name: make .aws dir
  shell: mkdir /home/ubuntu/.aws/

- name: Copy AWS config file
  template:
    src: config
    dest: /home/ubuntu/.aws/config
    mode: '0600'

- name: Copy AWS credentials file
  template:
    src: credentials
    dest: /home/ubuntu/.aws/credentials
    mode: '0600'

- name: Setting WEB_PRIVATE_IP as an environment variables
  shell: echo "export WEB_PRIVATE_IP=$(aws ec2 describe-instances --region us-east-1 --filters Name=tag:Name,Values=GoldenWasteWebApp --query 'Reservations[*].Instances[*].PrivateIpAddress' --output text)" >> ~/.profile

- name: Setting DB_PRIVATE_IP as an environment variables
  shell: echo "export DB_PRIVATE_IP=$(aws ec2 describe-instances --region us-east-1 --filters Name=tag:Name,Values=GoldenWasteDB --query 'Reservations[*].Instances[*].PrivateIpAddress' --output text)" >> ~/.profile