---
  - name: "Deploy jar file"
    hosts: GoldenWasteWebApp

    tasks:
    - name: Copy the file from master to GoldenWasteWebApp
      copy: src="/var/lib/jenkins/jobs/goldenwaste-sda-hackathon/builds/1/archive/target/goldenWastedd-0.0.1-SNAPSHOT.jar" dest="/home/ubuntu/ROOT.jar"

    - name: Set Linux environment variables
      environment:
        GOLDEN_DB_URL: 10.0.132.27
        GOLDEN_DB_PORT: 3306
        GOLDEN_DB_NAME: goldenwastedb
        GOLDEN_DB_USERNAME: root
        GOLDEN_DB_PASSWORD: DevOps@2022

    - name: Run JAR file
      shell: java -jar /home/ubuntu/ROOT.jar
      
    - name: Wait for WebApp to start
      wait_for: port=8080 timeout=60