---
  - name: "Install Jenkins Docker AWSCLI in localhost"
    hosts: localhost
    gather_facts: false
    connection: local
    tasks:

      - name: Install Maven
        become: yes
        apt:
          name: maven
          state: present
          update_cache: yes

      - name: Install apache2
        apt:
          name: apache2
          update_cache: yes
          state: latest

      - name: Install JDK
        apt:
          name: default-jdk
          update_cache: yes
          state: latest

      - name: Install Docker
        apt:
          name: docker.io
          update_cache: yes
          state: latest

      - name: Install AWSCLI
        apt:
          name: awscli
          update_cache: yes
          state: latest