---
  - name: Run Jenkins
    hosts: localhost
    become: yes
    gather_facts: false
    connection: local
    tasks:
      - name: Running Jenkins docker image
        shell: docker run -d -p 50000:50000 -p 8080:8080 --restart=on-failure --name jenkins jenkins/jenkins:lts-jdk11

      - name: Install Artifact Deployer Jenkins Plugin
        shell: docker exec -d jenkins jenkins-plugin-cli --plugins artifactdeployer:1.2