---
- name: Setup the Web App Server
  hosts: GoldenWasteWebApp
  become: yes
  become_method: sudo

  roles:
    - maven
    - java
    - nginx

- name: Setup the Database Server
  hosts: GoldenWasteDB
  become: yes
  become_method: sudo

  roles:
    - mysql

- name: Start Deploying
  hosts: GoldenWasteWebApp
  become: yes
  become_method: sudo

  roles:
    - deploy