---
- name: Install Java, maven and Nginx
  hosts: GoldenWasteWebApp
  become: yes
  become_method: sudo

  roles:
    - maven
    - java
    - nginx

- name: Install MySQL
  hosts: GoldenWasteDB
  become: yes
  become_method: sudo

  roles:
    - mysql

- name: Start Deploying
  hosts: GoldenWasteWebApp
  become: yes
  become_method: sudo

  roles:
    - deploy