---
- name: Setup the Web App Server
  hosts: GoldenWasteWebApp
  gather_facts: false
  become: yes
  become_method: sudo

  roles:
    - maven
    - java
    - nginx

- name: Setup the Database Server
  hosts: GoldenWasteDB
  gather_facts: false
  become: yes
  become_method: sudo

  roles:
    - docker
    - mysql

- name: Start Deploying
  hosts: GoldenWasteWebApp
  gather_facts: false
  become: yes
  become_user: ubuntu

  roles:
    - deploy