---
- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ mysql_container_name }}"
    source: pull

- name: Create default containers
  community.docker.docker_container:
    name: "{{ mysql_container_name }}"
    image: mysql
    ports: 3306:3306
    env:
      MYSQL_DATABASE: "{{ db_name }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_password }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
    state: "{{ mysql_state }}"
    restart_policy: unless-stopped
# sudo docker run --name mysql -e MYSQL_DATABASE=goldenwastedb -e MYSQL_USER=goldenwaste -e MYSQL_PASSWORD=DevOps2022 -e MYSQL_ROOT_PASSWORD=DevOps@2022 -p 3306:3306 -d --restart unless-stopped mysql