---
- name: Launch database container
  docker_container:
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ db_name }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_password }}"
    image: mysql
    labels:
      traefik.enable: "false"
    name: "{{ mysql_container_name }}"
    ports:
      - "{{ mysql_port }}:3306"
    pull: true
    recreate: true
    restart_policy: always
    state: "{{ mysql_state }}"

    # docker run --name MySQL -e MYSQL_ROOT_PASSWORD=DevOps@2022 -e MYSQL_DATABASE=goldenwastedb -e MYSQL_USER=goldenwaste -e MYSQL_PASSWORD=DevOps2022 -p 3306:3306 -d mysql