---
- name: Pull default Docker image
  community.docker.docker_image:
    name: "mysql"
    source: pull

- name: Create default containers
  community.docker.docker_container:
    name: "mysql"
    image: "mysql"
    ports: 3306:3306
    env:
      MYSQL_DATABASE: "goldenwastedb"
      MYSQL_USER: "goldenwaste"
      MYSQL_PASSWORD: "DevOps2022"
      MYSQL_ROOT_PASSWORD: "DevOps@2022"
    restart_policy: always
    state: started