---
- name: Create docker containers
  shell: sudo docker run --name mysql -e MYSQL_DATABASE=goldenwastedb -e MYSQL_USER=goldenwaste -e MYSQL_PASSWORD=DevOps2022 -e MYSQL_ROOT_PASSWORD=DevOps@2022 -p 3306:3306 -d --restart unless-stopped mysql