---
- name: Install python, pip, MySQL etc.
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - python3-pip
      - python3-dev
      - default-libmysqlclient-dev
      - build-essential
      - mysql-server
      - mysql-client

- name: pip install mysqlclient
  shell: pip install mysqlclient

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes
  when: ansible_selinux.status == "enabled"

- name: Create MySQL configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
  - restart mysql

- name: Start MySQL Service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Update MySQL root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items:
    - "{{ ansible_host }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Delete anonymous MySQL server user for localhost
  action:
    mysql_user:
      user: ""
      state: "absent"

- name: Remove the MySQL test database
  action:
    mysql_db:
      db: test
      state: absent

- name: Create a new database  
  mysql_db:
    name: {{ db_name }}
    state: present

- name: Create a new database user
  mysql_user:
    name: {{ db_user }}
    password: {{ db_password }}
    priv: {{ db_name }}.*:ALL
    host: 'localhost'
    state: present

- name: Restart MySQL
  service:
    name: mysqld
    state: restarted